# Generated by Django 5.1.6 on 2025-03-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="logtext",
            new_name="log_text",
        ),
    ]
