# Generated by Django 5.1.6 on 2025-03-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_rename_logtext_log_log_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="log",
            name="mood",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="log",
            name="sleep_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="sleep time"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="wakeup_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="wakeup time"
            ),
        ),
    ]
