# Generated by Django 5.1.6 on 2025-03-05 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_remove_log_pub_date_log_mood_log_sleep_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
