# Generated by Django 5.1.6 on 2025-03-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0004_log_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="sleep_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
