# Generated by Django 5.1.7 on 2025-10-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_log_sleep_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="good_1",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="良かったこと①"
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="good_2",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="良かったこと②"
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="good_3",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="良かったこと③"
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="growth",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="昨日から成長した点",
            ),
        ),
    ]
