# Generated by Django 5.1.7 on 2025-10-22 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0006_log_good_1_log_good_2_log_good_3_log_growth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="log_text",
            new_name="comment",
        ),
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, editable=False
            ),
        ),
    ]
