# Generated by Django 5.1.7 on 2025-10-22 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0007_rename_log_text_log_comment_alter_log_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
