# Generated by Django 5.1.7 on 2025-10-27 09:25

import django.utils.timezone
import logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0008_log_updated_at_alter_log_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=logs.models.Log.log_image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, unique=True
            ),
        ),
    ]
